version: "3.8"

services:
    postgres:
        image: postgres:alpine3.17
        restart: always
        container_name: db_user_service
        environment:
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            PGDATA: "${POSTGRES_DATA_FOLDER}"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data/
        ports:
            - "5432:5432"

    backend:
        build: .
        restart: always
        ports:
            - 8000:8000
        env_file:
            - .env
